In [3]:
import torch
import numpy as np
from torch.autograd import Variable as var

ModuleNotFoundError: No module named 'torch'

In [5]:
# tenor and numpy
## numpy 转化为torch的tensor的两种办法
numpy_tensor = np.random.randn(5, 20)
pytorch_tensor1 = torch.tensor(numpy_tensor)
pytorch_tensor2 = torch.from_numpy(numpy_tensor)
print(numpy_tensor, pytorch_tensor1, pytorch_tensor2)

[[-0.04201571 -1.03146311 -0.99324209  2.23482718  0.48731153  0.04141532
  -1.87805052  0.23430846  0.89011077 -2.40878108  0.76822011 -0.80727184
  -0.23139028  1.09034945  0.64625316 -0.73427032  1.71698982 -0.47911683
  -1.04346074  0.44238988]
 [-0.54721813  1.44165435 -0.03969733 -2.75559713  0.49706977  0.86670278
  -0.32585497  1.12179698 -1.17537943 -0.84064684 -0.50501519  1.17139473
   0.37041284 -1.20415734  1.15911531  0.32632547  1.10950109  1.09967516
   0.12099883 -1.07209097]
 [ 1.92242757  0.91221825  1.46721681  0.58711888 -1.08791583 -0.10710813
  -2.23264201  0.49413365 -0.64166269  0.27184266 -0.74354951 -0.22969058
  -1.42595282  1.14184497  0.32993744 -1.74405513  0.66325176  0.62165473
   2.75657771  1.88827242]
 [ 0.78623627  1.36798176  0.63751017 -0.13390405 -0.26573913  2.27166243
  -1.22809219  1.1004839  -0.42809814 -0.8377606  -0.95980261 -0.40412786
  -0.22005714  1.99172938  1.19272635 -0.45822569  0.81218832 -0.74867033
   0.79247226 -0.05058666]
 [-0

In [6]:
## tensor转为numpy数组
numpy_array = pytorch_tensor1.numpy() #在cpu上可以直接转换
numpy_array2 = pytorch_tensor1.cpu().numpy() #如果是在GPU上的tensor要先转化到CPU上
print(numpy_array, numpy_array2)

[[-0.04201571 -1.03146311 -0.99324209  2.23482718  0.48731153  0.04141532
  -1.87805052  0.23430846  0.89011077 -2.40878108  0.76822011 -0.80727184
  -0.23139028  1.09034945  0.64625316 -0.73427032  1.71698982 -0.47911683
  -1.04346074  0.44238988]
 [-0.54721813  1.44165435 -0.03969733 -2.75559713  0.49706977  0.86670278
  -0.32585497  1.12179698 -1.17537943 -0.84064684 -0.50501519  1.17139473
   0.37041284 -1.20415734  1.15911531  0.32632547  1.10950109  1.09967516
   0.12099883 -1.07209097]
 [ 1.92242757  0.91221825  1.46721681  0.58711888 -1.08791583 -0.10710813
  -2.23264201  0.49413365 -0.64166269  0.27184266 -0.74354951 -0.22969058
  -1.42595282  1.14184497  0.32993744 -1.74405513  0.66325176  0.62165473
   2.75657771  1.88827242]
 [ 0.78623627  1.36798176  0.63751017 -0.13390405 -0.26573913  2.27166243
  -1.22809219  1.1004839  -0.42809814 -0.8377606  -0.95980261 -0.40412786
  -0.22005714  1.99172938  1.19272635 -0.45822569  0.81218832 -0.74867033
   0.79247226 -0.05058666]
 [-0

In [11]:
## tensor转化导GPU上计算
gpu_tensor = torch.randn(10,20).cuda(0)#将tensor放到第一个gpu上
# gpu_tensor2 = torch.randn(10,20).cuda(1)#将tensor放到第二个gpu上,如果没有多块显卡报错
print(gpu_tensor)
cpu_tensor = gpu_tensor.cpu()
print(cpu_tensor)

tensor([[ 0.1923, -0.9185,  1.0112,  0.7913,  1.0885, -0.7639,  0.2820, -0.0087,
          0.5569,  0.7515, -1.1391,  0.0335, -0.4110,  0.9709, -1.1417,  0.7520,
         -2.0836,  0.1689, -1.2848, -0.5820],
        [-0.6657, -0.9849,  1.4465, -0.7792, -0.6676, -0.5991,  0.7583, -0.8425,
          2.9495,  0.2893, -0.2704,  0.7059,  1.7492, -1.6006, -1.3384, -1.0034,
         -1.3841,  1.6298,  0.3489,  0.6848],
        [-1.3480, -1.1660,  0.4786, -1.8046,  0.5877,  0.9384,  0.9224,  0.2839,
         -0.6237, -0.0499, -1.6318,  0.5280, -1.4194,  0.3315, -0.9152, -1.5580,
         -0.9447, -0.6809, -0.9559,  0.1122],
        [ 0.7240,  0.5458, -1.4345, -0.5413,  0.0420, -0.8908,  0.1923,  0.6055,
         -1.8411,  0.6131, -0.2499,  0.7314, -2.2424,  0.5047,  0.2121,  0.6339,
          0.7371,  1.5216,  1.2049, -0.4335],
        [-1.2291,  1.3583,  0.9024,  1.7938,  0.1902,  0.9020, -0.5145,  1.4689,
          0.4330, -2.0082, -0.8233,  1.9141, -0.7332, -0.0256,  0.0221, -1.4386,
      

In [14]:
# tensor的基本用法
## 得到tensor的大小
print(pytorch_tensor1.shape)#属性
print(pytorch_tensor1.size())#方法

torch.Size([5, 20])
torch.Size([5, 20])


In [15]:
## 得到tensor的数据类型
pytorch_tensor1.type()

'torch.DoubleTensor'

In [16]:
## 得到tensor维度
pytorch_tensor1.dim()

2

In [18]:
## 得到tensor所有元素个数
pytorch_tensor1.numel()

100

In [19]:
## 创建全为1的tensor
x = torch.ones(2,2)
print(x)
print(x.type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor


In [21]:
## 将tensor转化特定类型
x = torch.ones(2,2)
print(x)
print(x.type())
x = x.int()#这里可以写任意支持的类型，long、float等
print(x)
print(x.type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.IntTensor


In [22]:
## 生成随机数据
x = torch.randn(4, 3)
print(x)

tensor([[ 0.8918,  1.9159,  0.0298],
        [ 0.0556, -0.2020,  1.0884],
        [ 1.8685, -0.1276,  1.5608],
        [ 0.0374, -1.1993, -0.8290]])


In [23]:
## 寻找矩阵中每行中最大值及其索引
max_value, max_idx = torch.max(x , dim=1)
print(max_value)
print(max_idx)

tensor([1.9159, 1.0884, 1.8685, 0.0374])
tensor([1, 2, 0, 0])


In [34]:
## 增加/减少tensor的维度
x = torch.ones(2, 2)
print(x.shape)
x = x.unsqueeze(0)#增加第一维度
print(x.shape)
x = x.unsqueeze(-1)#最后增加一维度
print(x.shape)
x = x.squeeze(0)#减少一维度
print(x.shape)
x = x.squeeze()#去掉所有一维的维度
print(x.shape)

torch.Size([2, 2])
torch.Size([1, 2, 2])
torch.Size([1, 2, 2, 1])
torch.Size([2, 2, 1])
torch.Size([2, 2])


In [35]:
## tensor的维度排列
x = torch.randn(3, 4, 5)
print(x.shape)
x = x.permute(1, 0, 2)#重新排列维度
print(x.shape)
x = x.transpose(0, 2)#交换维度
print(x.shape)


torch.Size([3, 4, 5])
torch.Size([4, 3, 5])
torch.Size([5, 3, 4])


In [36]:
## tensor的维度转化
x = torch.randn(3, 4, 5)
print(x.shape)
x = x.view(-1, 2)#-1表示根据其他维度自行确认该维度
print(x.shape)
x = x.view(3, 20)#转化为指定维度
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([30, 2])
torch.Size([3, 20])


In [38]:
## torch的inplace操作（在操作符后加下划线“_”）
x = torch.randn(3,4,5)
print(x.shape)
x.unsqueeze_(0)
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([1, 3, 4, 5])


In [ ]:
# Variable的基本用法与自动求导
'''
（1）Variable.data ：data属性即是本身的Tensor；
（2）Variable.grad：通过反向传播后，grad属性即是梯度指；
（3）Variable.grad_fn：构建过程及方式即Variable的grad_fn属性
'''

In [42]:
from torch.autograd import Variable as var

In [49]:
## tnsor转化为variable
x_tensor = torch.randn(10, 5)
y_tensor = torch.randn(10, 5)
x = var(x_tensor, requires_grad = True) #requires_grad求梯度参数，true表示求
print(x.grad, x)
y = var(y_tensor, requires_grad = True)
print(y.grad, y)

None tensor([[-1.6671e-01, -1.8077e+00,  7.8527e-03, -4.3268e-01, -2.1746e-02],
        [-5.4532e-01, -1.2035e+00,  1.9933e+00,  8.6060e-01,  1.7089e+00],
        [-2.6111e+00, -1.8163e+00,  4.2904e-01, -1.5935e+00,  8.2917e-01],
        [ 1.3152e+00,  2.1132e+00, -1.4593e+00, -2.5849e-01, -8.4379e-01],
        [ 5.5118e-01, -1.0175e-01, -1.7066e+00,  1.5090e+00,  5.6854e-01],
        [-1.0335e+00, -1.4276e-01,  4.5841e-01,  2.1120e-01, -2.3750e-02],
        [ 2.9842e-01, -1.9570e+00, -1.1439e-01,  3.1577e-01, -9.7095e-01],
        [-6.4953e-01, -1.8488e+00,  1.0312e+00, -2.4716e-01,  1.0454e-01],
        [-5.4660e-01, -1.1391e+00, -1.7222e-03, -1.3096e+00,  2.9963e-01],
        [ 5.1791e-01,  4.1057e-01, -6.1578e-01, -5.6396e-01, -5.2962e-01]],
       requires_grad=True)
None tensor([[ 0.5282,  0.6060, -0.7697,  1.2066, -1.5311],
        [-1.6528,  0.7665, -0.6950,  1.6728, -1.6597],
        [ 0.8511, -0.0610, -0.7873,  1.8583, -0.7553],
        [ 0.9959, -0.5003, -1.3746,  1.2092, -0

In [50]:
## variable的运算
z = torch.sum(x + y)
print(z.data) #data属性即是本身的Tensor；
print(z.grad_fn) #构建过程及方式即Variable的grad_fn属性

tensor(-7.1171)


In [51]:
## 求z关于梯度x和y的梯度值
z.backward()
print(x.grad) #前面刚建立x，y是没grad的，backward之后才有grad，因为backward才链式求导了
print(y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [57]:

## torch的自动求导
'''定义一个简单函数并初始化'''
x = var(torch.Tensor([2]), requires_grad = True)#注意这了是大写T，小写t就成了转化
y = x + 2
z = y ** 2 + 3
print(x)
print(z)
z.backward()
print(x.grad)

tensor([2.], requires_grad=True)
tensor([19.], grad_fn=<AddBackward0>)
tensor([8.])


In [60]:
'''定义一个复杂函数并初始化'''
x = var(torch.randn(10, 20), requires_grad = True)#10rows,20columns
y = var(torch.randn(10, 5), requires_grad = True)#10rows,5columns,reflect to rows of x
w = var(torch.randn(20, 5), requires_grad = True)#20rows,xcolumns,reflect to columns of x
out = torch.mean(y - torch.matmul(x, w))
out.backward()
print(x)
print('~'*50)
print(x.grad)
print('~'*50)
print(out)

tensor([[-0.3869, -1.8441,  0.1833, -0.1408, -0.2587, -0.7610, -2.1376,  0.6763,
         -1.0739, -0.6241, -0.0241, -2.1187,  0.4243,  0.0054,  0.9501,  0.2229,
         -0.0790,  0.8490, -0.1119,  0.2383],
        [-0.1852, -0.3263, -0.6571,  1.0523,  0.9925,  0.2280, -0.1788, -0.9651,
         -0.6667, -0.2314, -0.0356, -0.5279,  0.7396,  0.7772, -1.3920, -2.9456,
          1.4288,  0.5675, -0.0079, -0.0601],
        [ 1.7998, -1.2727,  0.2236,  0.5868,  1.3777, -0.2302, -0.6145,  1.2788,
          0.0730,  0.7921,  0.6467, -1.0261, -0.9977, -0.5089,  1.0232, -0.9956,
          0.3353, -0.9120,  0.1259, -1.5256],
        [-0.9210, -0.1081, -0.6501,  0.3461,  1.3688, -0.7816, -0.8096,  0.4614,
         -0.9482,  1.2167, -0.8059, -0.8693,  1.4616,  2.6624,  0.3813,  1.0205,
         -0.4351,  1.0234,  0.4509,  0.2319],
        [ 1.4200, -0.6489, -0.0927, -0.5744,  1.5813,  0.4184,  0.3568, -0.0103,
          1.0604,  0.0713,  0.1955,  1.1796, -0.0345, -1.7936, -1.5906, -0.1566,
      

In [59]:
# 数据预处理
## 读取数据


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
